### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by SheepCommander** [RazerMoon/hidechannels#1]
![image](https://user-images.githubusercontent.com/66646514/148945359-36f66da2-5173-4f67-a65a-548155957221.png)

**Comment by RazerMoon** [comment]
New discord update is apparently going all wacky.

Looks like the `GuildContextMenu` component doesn't immediately load anymore.

I could *maybe* force it to load manually, but idk how and I'm lazy. So, the dropdown in the CM's going away temporarily.

(Update to newest for fix)
