### ISSUE TITLE
Plugin Broke

### ISSUE THREAD

**Issue by DracoClaw** [RazerMoon/hidechannels#2]
So when I click the Hide Channel button nothing happens. The channel stays visible in the list.

**Comment by DracoClaw** [comment]
IDK why I didn't include this but this is the error.
`Tried to patch undefined (Injection ID "hidechannels-navchannels-patch")`

**Comment by Mioni** [comment]
This plugin is very useful
I miss him... :l

**Comment by RazerMoon** [comment]
Now that Powercord has reached EOL I'm sadly discontinuing support of all of my PC plugins 😔. I suggest you guys move to a different client.

**Comment by DracoClaw** [comment]
Only the Powercord dev branch is EOL. Development has moved over to [Replugged](https://github.com/replugged-org/replugged). Which is the same source as PC but updated and maintained.
